var aNavItemDate = [
	[
		{
			url:'https://www.kuazhu.com',
			img:'image/p1.jpg',
			name:'小米MIX 3',
			price:'3299元起',
			flag:'新品',
		},
		{
			url:'https://www.kuazhu.com',
			img:'image/p2.jpg',
			name:'小米MIX 3',
			price:'3299元起',
			flag:'新品',
		},
		{
			url:'https://www.kuazhu.com',
			img:'image/p1.jpg',
			name:'小米MIX 3',
			price:'3299元起',
			flag:'新品',
		},
	],
	[
		{
			url:'https://www.kuazhu.com',
			img:'image/p1.jpg',
			name:'小米MIX 2',
			price:'3299元起',
			flag:'新品',
		},
		{
			url:'https://www.kuazhu.com',
			img:'image/p1.jpg',
			name:'小米MIX 2',
			price:'3299元起',
			flag:'新品',
		},
		{
			url:'https://www.kuazhu.com',
			img:'image/p1.jpg',
			name:'小米MIX 2',
			price:'3299元起',
			flag:'新品',
		},
	],
	[
		{
			url:'https://www.kuazhu.com',
			img:'image/p1.jpg',
			name:'小米MIX 3',
			price:'3299元起',
			flag:'新品',
		},
		{
			url:'https://www.kuazhu.com',
			img:'image/p2.jpg',
			name:'小米MIX 3',
			price:'3299元起',
			flag:'新品',
		},
		{
			url:'https://www.kuazhu.com',
			img:'image/p1.jpg',
			name:'小米MIX 3',
			price:'3299元起',
			flag:'新品',
		},
	],
	[
		{
			url:'https://www.kuazhu.com',
			img:'image/p1.jpg',
			name:'小米MIX 2',
			price:'3299元起',
			flag:'新品',
		},
		{
			url:'https://www.kuazhu.com',
			img:'image/p1.jpg',
			name:'小米MIX 2',
			price:'3299元起',
			flag:'新品',
		},
		{
			url:'https://www.kuazhu.com',
			img:'image/p1.jpg',
			name:'小米MIX 2',
			price:'3299元起',
			flag:'新品',
		},
	],
	[
		{
			url:'https://www.kuazhu.com',
			img:'image/p1.jpg',
			name:'小米MIX 3',
			price:'3299元起',
			flag:'新品',
		},
		{
			url:'https://www.kuazhu.com',
			img:'image/p2.jpg',
			name:'小米MIX 3',
			price:'3299元起',
			flag:'新品',
		},
		{
			url:'https://www.kuazhu.com',
			img:'image/p1.jpg',
			name:'小米MIX 3',
			price:'3299元起',
			flag:'新品',
		},
	],
	[
		{
			url:'https://www.kuazhu.com',
			img:'image/p1.jpg',
			name:'小米MIX 2',
			price:'3299元起',
			flag:'新品',
		},
		{
			url:'https://www.kuazhu.com',
			img:'image/p1.jpg',
			name:'小米MIX 2',
			price:'3299元起',
			flag:'新品',
		},
		{
			url:'https://www.kuazhu.com',
			img:'image/p1.jpg',
			name:'小米MIX 2',
			price:'3299元起',
			flag:'新品',
		},
	],
	[
		{
			url:'https://www.kuazhu.com',
			img:'image/p1.jpg',
			name:'小米MIX 3',
			price:'3299元起',
			flag:'新品',
		},
		{
			url:'https://www.kuazhu.com',
			img:'image/p2.jpg',
			name:'小米MIX 3',
			price:'3299元起',
			flag:'新品',
		},
		{
			url:'https://www.kuazhu.com',
			img:'image/p1.jpg',
			name:'小米MIX 3',
			price:'3299元起',
			flag:'新品',
		},
	],
	[
		{
			url:'https://www.kuazhu.com',
			img:'image/p1.jpg',
			name:'小米MIX 2',
			price:'3299元起',
			flag:'新品',
		},
		{
			url:'https://www.kuazhu.com',
			img:'image/p1.jpg',
			name:'小米MIX 2',
			price:'3299元起',
			flag:'新品',
		},
		{
			url:'https://www.kuazhu.com',
			img:'image/p1.jpg',
			name:'小米MIX 2',
			price:'3299元起',
			flag:'新品',
		},
	]
]